### ISSUE TITLE
Windows installation problems

### ISSUE THREAD

**Issue by stucka** [tpeng/python-crfsuite#16]
I'm trying to get python-crfsuite installed on Python 2.7 32-bit on a Windows 7 64-bit machine. It's not working, to put it mildly: gets caught up at crf1d_model.c looking to include stdint.h (no such file or directory). I've tried editing a 0.8.2 archive and thrown that stdint.h file pretty much everywhere without success. I've tried forcing installs as early as 0.7.0, the earliest package I can use for a project, without success. Any ideas?

I can't find where anyone's had this error before. In fact, I could only find a couple references to people having any problems getting this installed on Windows; one guy never got an answer, and the other is on what's now a defunct blog in Russia.

I've posted an error log here:
https://gist.github.com/stucka/f99828073acf622d2982

**Comment by tpeng** [comment]
from the log seems like the compiler is not c99 compliant, that's why the stdint.h is missing.  google the `Visual C++ for Python stdint.h` found this: `Finally download the stdint.h header from here and save it as C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\include\stdint.h.` see http://deeplearning.net/software/theano/install_windows.html. hope it helps. good luck!

**Comment by kmike** [comment]
@tpeng is right that the issue is with MSVC not having stdint.h header.
But CRFSuite library ships with a portable stdint.h header for Windows - see https://github.com/chokkan/crfsuite/tree/master/win32. Maybe we can make python-crfsuite use it.

**Comment by stucka** [comment]
I'm not sure what the production answer is, but I was able to get it working by adapting @tpeng 's original suggestion. Dropping the file here worked:
C:\Users\mstucka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include

It failed here, which is the closest I could find to the originally suggested path:
 C:\Program Files (x86)\Common Files\microsoft shared\VC

I used the file from crfsuite-0.12.tar.gz\crfsuite-0.12.tar\crfsuite-0.12\win32 ...

Please scream if I can help troubleshoot a production answer. I'd run into the problem with an Anaconda distribution and wiped that out in favor of the regular Python distribution, where I also ran into the same problem.

**Comment by tpeng** [comment]
@kmike i'm ok with that. :+1:
