### ISSUE TITLE
cross validation in trainer

### ISSUE THREAD

**Issue by xuchen** [tpeng/python-crfsuite#22]
Thanks for providing such an excellent wrapper. The original trainer can do CV on the fly (-x option). Do you have plans to support this options? Thanks!

**Comment by kmike** [comment]
Hey @xuchen,

There is some support for cross-validation: when loading data to Trainer, you can assign a group ID to it (see 'group' argument of [Trainer.append](http://python-crfsuite.readthedocs.org/en/latest/pycrfsuite.html#pycrfsuite.Trainer.append)). Then, at training time, you can set a group ID to use as a holdout data (see 'holdout' argument of [Trainer.train](http://python-crfsuite.readthedocs.org/en/latest/pycrfsuite.html#pycrfsuite.Trainer.train)). So to perform cross-validation you can split your data into 10 groups when loading, and then run Trainer.train 10 times, passing different holdout group ID values. This is what CRFSuite command-line utility doing.

Another option is to use scikit-learn cross validation utilities. You can wrap Trainer and Tagger into an object which conforms to scikit-learn interface (examples: [first](https://github.com/scrapinghub/webstruct/blob/master/webstruct/crfsuite.py), [second](https://github.com/kmike/morphine/blob/master/morphine/crfsuite.py)) and then use [utilities](http://scikit-learn.org/stable/modules/cross_validation.html) from scikit-learn.

**Comment by xuchen** [comment]
Thanks! The 2nd example you gave was extremely helpful!

**Comment by Kureman** [comment]
I was wondering about this and I just would like to know if doing it this way (after splitting the corpus) actually updates the previous model or deletes it: 

`for i in range(10):
    trainer.train('crf.model', holdout=i)`

Thanks
