### ISSUE TITLE
How to regenerate _pycrfsuite.cpp file from _pycrfsuite.pyx 

### ISSUE THREAD

**Issue by happywwy** [tpeng/python-crfsuite#25]
Hi,

I made some minor changes in crfsuite library and as well as pyx cython file. But I cannot re-generate the cpp file from the new pyx file. I cannot find any setup script for building cython code. May I know how to do that? Or anyone could post this setup file? Thanks!

Regards,
Wenya

**Comment by kmike** [comment]
Hey @happywwy,

* to generate cpp files from pyx files use https://github.com/tpeng/python-crfsuite/blob/master/update_cpp.sh script; 
* build compile the extension run `setup.py install` from repo root, as usual.

Hope this helps!
